Models/BankAccount.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CarScope.Models
{
    public class BankAccount
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string AccNo { get; set; }

        public decimal AvailableBal { get; set; }

    }
    public class BankDeposit
    {
        public int ID { get; set; }
        public string AccNo { get; set; }
        public string Narration { get; set; }
        public decimal Amount { get; set; }
        public decimal Balance { get; set; }
    }
    public class BankWithDrawal
    {
        public int ID { get; set; }
        public string AccNo { get; set; }
        public string Narration { get; set; }
        public decimal Amount { get; set; }
        public decimal Balance { get; set; }
    }
    public class BankTransfer
    {
        public int ID { get; set; }
        public string AccNo { get; set; }
        public decimal Amount { get; set; }
        public string Narration { get; set; }
        public string AccNo2 { get; set; }
        
        
    }
    public class InterBankTransfer
    {
        public int ID { get; set; }
        public string AccNo { get; set; }
        public decimal AvailableBal { get; set; }
        public string Narration { get; set; }
        public string AccNo2 { get; set; }
        public decimal TransferAmount { get; set; }


    }
}

Controllers/BankAccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CarScope.Data;
using CarScope.Models;

namespace CarScope.Controllers
{
    public class BankAccountsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BankAccountsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: BankAccounts
        public async Task<IActionResult> Index()
        {
            return View(await _context.BankAccount.ToListAsync());
        }

        // GET: BankAccounts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bankAccount = await _context.BankAccount
                .FirstOrDefaultAsync(m => m.ID == id);
            if (bankAccount == null)
            {
                return NotFound();
            }

            return View(bankAccount);
        }

        // GET: BankAccounts/Create
        public IActionResult Create()
        {
            Random rn = new Random();
            BankAccount bn = new BankAccount()
            {
                AccNo = rn.Next().ToString()
            };
            
            return View(bn);
        }

        // POST: BankAccounts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,AccNo,AvailableBal")] BankAccount bankAccount)
        {
            if (ModelState.IsValid)
            {
                _context.Add(bankAccount);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(bankAccount);
        }

        // GET: BankAccounts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bankAccount = await _context.BankAccount.FindAsync(id);
            if (bankAccount == null)
            {
                return NotFound();
            }

            return View(bankAccount);
        }

        // POST: BankAccounts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,AccNo,AvailableBal")] BankAccount bankAccount)
        {
            if (id != bankAccount.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bankAccount);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BankAccountExists(bankAccount.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(bankAccount);
        }

        // GET: BankAccounts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bankAccount = await _context.BankAccount
                .FirstOrDefaultAsync(m => m.ID == id);
            if (bankAccount == null)
            {
                return NotFound();
            }

            return View(bankAccount);
        }

        // POST: BankAccounts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bankAccount = await _context.BankAccount.FindAsync(id);
            _context.BankAccount.Remove(bankAccount);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BankAccountExists(int id)
        {
            return _context.BankAccount.Any(e => e.ID == id);
        }
    }
}

Controllers/InterBankTransfersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CarScope.Data;
using CarScope.Models;

namespace CarScope.Controllers
{
    public class InterBankTransfersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public InterBankTransfersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: InterBankTransfers
        public async Task<IActionResult> Index()
        {
            return View(await _context.InterBankTransfer.ToListAsync());
        }

        // GET: InterBankTransfers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var interBankTransfer = await _context.InterBankTransfer
                .FirstOrDefaultAsync(m => m.ID == id);
            if (interBankTransfer == null)
            {
                return NotFound();
            }

            return View(interBankTransfer);
        }

        // GET: InterBankTransfers/Create
        public async Task<IActionResult> Create(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bankAccount = await _context.BankAccount.FindAsync(id);
            if (bankAccount == null)
            {
                return NotFound();
            }
            var BcK = new InterBankTransfer()
            {
                AccNo = bankAccount.AccNo,
                AvailableBal = bankAccount.AvailableBal
            };
            return View(BcK);
        }
        public async Task DeductionAsync(string abc, decimal def)
        {
            //deduction from account
            var bDel = (from a in _context.BankAccount
                        where a.AccNo == abc
                        select a).FirstOrDefault();

            bDel.AvailableBal -= def;
            _context.Entry(bDel).State = EntityState.Modified;
            await _context.SaveChangesAsync();
        }
        // POST: InterBankTransfers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,AccNo,AvailableBal,Narration,AccNo2,TransferAmount")] InterBankTransfer interBankTransfer)
        {
            if (ModelState.IsValid)
            {
                var bDel = (from a in _context.BankAccount
                            where a.AccNo == interBankTransfer.AccNo
                            select a).FirstOrDefault();
                if (interBankTransfer.TransferAmount < bDel.AvailableBal)
                {
                    var bTran = (from a in _context.BankAccount
                                 where a.AccNo == interBankTransfer.AccNo2
                                 select a).FirstOrDefault();

                    bTran.AvailableBal += interBankTransfer.TransferAmount;
                    _context.Entry(bTran).State = EntityState.Modified;
                    await DeductionAsync(interBankTransfer.AccNo, interBankTransfer.TransferAmount);



                    await _context.SaveChangesAsync();
                    return RedirectToAction("Index", "BankAccounts", null);
                }
                //addition to another account
                else
                {
                    ViewBag.Message = string.Format("Hello {0}.\nthe current transfer amount {1} is higher than {2}, \ninsufficient funds", DateTime.Now.ToString(), interBankTransfer.TransferAmount, bDel.AvailableBal);
                    return View(interBankTransfer);
                }
                
                
            }
            return View(interBankTransfer);
        }

        // GET: InterBankTransfers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var interBankTransfer = await _context.InterBankTransfer.FindAsync(id);
            if (interBankTransfer == null)
            {
                return NotFound();
            }
            return View(interBankTransfer);
        }

        // POST: InterBankTransfers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,AccNo,AvailableBal,Narration,AccNo2,TransferAmount")] InterBankTransfer interBankTransfer)
        {
            if (id != interBankTransfer.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(interBankTransfer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InterBankTransferExists(interBankTransfer.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(interBankTransfer);
        }

        // GET: InterBankTransfers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var interBankTransfer = await _context.InterBankTransfer
                .FirstOrDefaultAsync(m => m.ID == id);
            if (interBankTransfer == null)
            {
                return NotFound();
            }

            return View(interBankTransfer);
        }

        // POST: InterBankTransfers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var interBankTransfer = await _context.InterBankTransfer.FindAsync(id);
            _context.InterBankTransfer.Remove(interBankTransfer);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool InterBankTransferExists(int id)
        {
            return _context.InterBankTransfer.Any(e => e.ID == id);
        }
    }
}

Views/BankAccounts/Create.cshtml
@model CarScope.Models.BankAccount

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>BankAccount</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AccNo" class="control-label"></label>
                <input asp-for="AccNo" class="form-control" />
                <span asp-validation-for="AccNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AvailableBal" class="control-label"></label>
                <input asp-for="AvailableBal" class="form-control" />
                <span asp-validation-for="AvailableBal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/BankAccounts/Delete.cshtml
@model CarScope.Models.BankAccount

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BankAccount</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AccNo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AccNo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AvailableBal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AvailableBal)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/BankAccounts/Details.cshtml
@model CarScope.Models.BankAccount

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>BankAccount</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AccNo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AccNo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AvailableBal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AvailableBal)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/BankAccounts/Edit.cshtml
@model CarScope.Models.BankAccount

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>BankAccount</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AccNo" class="control-label"></label>
                <input asp-for="AccNo" class="form-control" />
                <span asp-validation-for="AccNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AvailableBal" class="control-label"></label>
                <input asp-for="AvailableBal" class="form-control" />
                <span asp-validation-for="AvailableBal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/BankAccounts/Index.cshtml
@model IEnumerable<CarScope.Models.BankAccount>

@{
    ViewData["Title"] = "Index";
}
<style>
    #viewContent {
        padding-left: 20px;
    }

        #viewContent select, #viewContent button {
            font-size: 25px;
        }

        #viewContent h4 {
            margin: 10px 0;
        }

        #viewContent .textAlignCenter {
            text-align: center;
        }

            #viewContent .textAlignCenter img {
                display: none;
                width: 100px;
            }

        #viewContent #message table {
            width: 100%;
        }

            #viewContent #message table th {
                text-align: left;
                text-decoration: underline;
            }
</style>
<select id="citySelect">
    <option value="Select">Select</option>
    <option value="5128581">New York</option>
    <option value="5391959">San Francisco</option>
    <option value="London">London</option>
    <option value="1275339">Mumbai</option>
    <option value="8199396">Santa Lucia</option>
</select>

<button id="submit">Submit</button>
<div class="textAlignCenter">
    <img src="https://cdnjs.cloudflare.com/ajax/libs/jquery-mobile/1.4.5/images/ajax-loader.gif" />
</div>
<div id="message"></div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $("#submit").click(function (e) {
            var validate = Validate();
            $("#message").html(validate);
            if (validate.length == 0) {
                $.ajax({
                    type: "POST",
                    url: "https://api.openweathermap.org/data/2.5/weather?id=" + $("#citySelect").val() + "&appid=2efe69b302d9dc2ac48cd97fb8043dad",
                    dataType: "json",
                    success: function (result, status, xhr) {
                        var table = $("<table><tr><th>Weather Description</th></tr>");

                        table.append("<tr><td>City:</td><td>" + result["name"] + "</td></tr>");
                        table.append("<tr><td>Country:</td><td>" + result["sys"]["country"] + "</td></tr>");
                        table.append("<tr><td>Current Temperature:</td><td>" + result["main"]["temp"] + "°C</td></tr>");
                        table.append("<tr><td>Humidity:</td><td>" + result["main"]["humidity"] + "</td></tr>");
                        table.append("<tr><td>Weather:</td><td>" + result["weather"][0]["description"] + "</td></tr>");

                        $("#message").html(table);
                    },
                    error: function (xhr, status, error) {
                        alert("Result: " + status + " " + error + " " + xhr.status + " " + xhr.statusText)
                    }
                });
            }
        });

        $(document).ajaxStart(function () {
            $("img").show();
        });

        $(document).ajaxStop(function () {
            $("img").hide();
        });

        function Validate() {
            var errorMessage = "";
            if ($("#citySelect").val() == "Select") {
                errorMessage += "► Select City";
            }
            return errorMessage;
        }
    });
</script>
<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AccNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AvailableBal)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AccNo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AvailableBal)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                    <a asp-action="Create" asp-controller="InterBankTransfers" asp-route-id="@item.ID">Transfer</a> |
                    <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>